2025-04-06 17:47:07,684 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:48:26,723 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:48:27,713 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:57:27,502 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:58:12,333 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:59:11,577 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 17:59:35,561 ERROR: Erro ao criar tarefa: 'Tarefa' object has no attribute 'shared_with' [in C:\Python\AdGest\app\routes.py:338]
2025-04-06 18:06:17,302 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:06:50,987 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:07:48,102 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:08:21,854 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:09:58,381 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:10:47,517 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:11:18,111 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:23:55,992 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:25:19,524 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:26:16,553 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:26:52,505 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:28:52,894 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:48:45,095 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:49:08,804 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:49:36,513 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:49:41,414 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:49:42,522 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 18:56:26,857 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:02:29,331 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:06:03,707 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:17:22,403 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:18:02,199 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:24:08,168 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:26:08,363 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:26:09,349 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:28:11,816 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:28:26,064 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:28:27,040 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:29:06,268 INFO: Tentando atualizar assunto 11 para ordem 0 [in C:\Python\AdGest\app\routes.py:699]
2025-04-06 19:29:06,268 WARNING: Assunto 11 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:704]
2025-04-06 19:44:39,270 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:56:11,730 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 19:56:12,655 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-06 20:06:29,850 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-07 00:25:26,910 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-07 00:25:29,164 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-07 23:20:55,722 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-07 23:20:58,297 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:08:03,197 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:08:05,735 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:21:38,524 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:27:34,186 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:30:19,440 INFO: Tentando atualizar assunto 5 para ordem 0 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,441 INFO: Assunto 5 atualizado com nova ordem 0 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,447 INFO: Tentando atualizar assunto 10 para ordem 1 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,448 WARNING: Assunto 10 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,451 INFO: Tentando atualizar assunto 7 para ordem 2 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,452 INFO: Assunto 7 atualizado com nova ordem 2 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,457 INFO: Tentando atualizar assunto 3 para ordem 3 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,458 WARNING: Assunto 3 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,466 INFO: Tentando atualizar assunto 6 para ordem 4 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,467 WARNING: Assunto 6 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,471 INFO: Tentando atualizar assunto 13 para ordem 5 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,472 INFO: Assunto 13 atualizado com nova ordem 5 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,478 INFO: Tentando atualizar assunto 4 para ordem 6 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,481 WARNING: Assunto 4 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,485 INFO: Tentando atualizar assunto 11 para ordem 7 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,486 WARNING: Assunto 11 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,489 INFO: Tentando atualizar assunto 16 para ordem 8 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,489 INFO: Assunto 16 atualizado com nova ordem 8 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,492 INFO: Tentando atualizar assunto 15 para ordem 9 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,493 WARNING: Assunto 15 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,497 INFO: Tentando atualizar assunto 12 para ordem 10 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,499 WARNING: Assunto 12 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,502 INFO: Tentando atualizar assunto 14 para ordem 11 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,503 INFO: Assunto 14 atualizado com nova ordem 11 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,507 INFO: Tentando atualizar assunto 2 para ordem 12 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,507 INFO: Assunto 2 atualizado com nova ordem 12 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,512 INFO: Tentando atualizar assunto 8 para ordem 13 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,515 WARNING: Assunto 8 não encontrado ou não pertence ao usuário 1 [in C:\Python\AdGest\app\routes.py:761]
2025-04-08 00:30:19,517 INFO: Tentando atualizar assunto 9 para ordem 14 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,518 INFO: Assunto 9 atualizado com nova ordem 14 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:30:19,520 INFO: Tentando atualizar assunto 1 para ordem 15 [in C:\Python\AdGest\app\routes.py:756]
2025-04-08 00:30:19,521 INFO: Assunto 1 atualizado com nova ordem 15 [in C:\Python\AdGest\app\routes.py:759]
2025-04-08 00:33:07,821 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:43:21,174 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 00:53:20,354 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:11:12,971 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:11:21,002 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:11:55,135 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:11:57,165 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:19:12,279 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:20:12,676 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:24:47,050 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:25:50,168 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:26:55,320 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:37:59,923 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:38:09,905 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:38:17,329 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:42:27,142 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:42:29,462 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 01:43:44,173 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
2025-04-08 02:05:15,325 INFO: Debug AdGest startup [in C:\Python\AdGest\app\__init__.py:52]
